//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinigentAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class qt_infinigentdbEntities : DbContext
    {
        public qt_infinigentdbEntities()
            : base("name=qt_infinigentdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LU_Challan_Type_t> LU_Challan_Type_t { get; set; }
        public virtual DbSet<LU_Comments_Type_t> LU_Comments_Type_t { get; set; }
        public virtual DbSet<LU_Commnets_t> LU_Commnets_t { get; set; }
        public virtual DbSet<LU_Configaration_Settings_t> LU_Configaration_Settings_t { get; set; }
        public virtual DbSet<LU_Device_Info_t> LU_Device_Info_t { get; set; }
        public virtual DbSet<LU_Employee_t> LU_Employee_t { get; set; }
        public virtual DbSet<LU_Outlate_Type_t> LU_Outlate_Type_t { get; set; }
        public virtual DbSet<LU_Scheme_Media_Type_t> LU_Scheme_Media_Type_t { get; set; }
        public virtual DbSet<LU_Scheme_Name_t> LU_Scheme_Name_t { get; set; }
        public virtual DbSet<LU_User_Login_Ids_t> LU_User_Login_Ids_t { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TRN_Scheme_Audit_Child_t> TRN_Scheme_Audit_Child_t { get; set; }
        public virtual DbSet<TRN_Scheme_Audit_Parent_t> TRN_Scheme_Audit_Parent_t { get; set; }
        public virtual DbSet<LU_User_t> LU_User_t { get; set; }
    }
}
