//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinigentAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_Asset_Config_Photos
    {
        public int Id { get; set; }
        public string AssetNumber { get; set; }
        public string ShopImage { get; set; }
        public string AssetImage { get; set; }
        public string SignImage { get; set; }
        public string CoolerImage { get; set; }
        public string ShortNote { get; set; }
        public string Remarks { get; set; }
    }
}
