//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinigentAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_Asset_Config
    {
        public int Id { get; set; }
        public string AssetNumber { get; set; }
        public string SerialNumber { get; set; }
        public string DistributorId { get; set; }
        public string DistributorName { get; set; }
        public string AICName { get; set; }
        public string ASMName { get; set; }
        public string MDOId { get; set; }
        public string MDOName { get; set; }
        public string OutletId { get; set; }
        public string OutletName { get; set; }
        public string OutletAddress { get; set; }
        public string ContactNo { get; set; }
        public string CoolerModel { get; set; }
        public Nullable<bool> NightCover { get; set; }
        public Nullable<bool> IsRepeated { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public string Device_Number { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> ModifierId { get; set; }
        public System.DateTime ModificationDate { get; set; }
    }
}
