//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinigentAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_Item
    {
        public int Id { get; set; }
        public string ItemCode { get; set; }
        public string Name { get; set; }
        public int ItemGroupId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> ModifierId { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
    
        public virtual LU_Category LU_Category { get; set; }
        public virtual LU_ItemGroup LU_ItemGroup { get; set; }
    }
}
