//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinigentAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_ScreenDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LU_ScreenDetail()
        {
            this.TRN_PermissionDetail = new HashSet<TRN_PermissionDetail>();
        }
    
        public int ScreenDetailId { get; set; }
        public int ScreenId { get; set; }
        public int FunctionId { get; set; }
    
        public virtual LU_Screen LU_Screen { get; set; }
        public virtual LU_ScreenFunction LU_ScreenFunction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_PermissionDetail> TRN_PermissionDetail { get; set; }
    }
}
