//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinigentAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class qt_infinigentdbEntities1 : DbContext
    {
        public qt_infinigentdbEntities1()
            : base("name=qt_infinigentdbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TRN_AssetAudit> TRN_AssetAudit { get; set; }
        public virtual DbSet<TRN_AssetAuditNumber> TRN_AssetAuditNumber { get; set; }
        public virtual DbSet<LU_AssetInfo> LU_AssetInfo { get; set; }
        public virtual DbSet<LU_AssetInfo_Log> LU_AssetInfo_Log { get; set; }
        public virtual DbSet<LU_Cooler> LU_Cooler { get; set; }
        public virtual DbSet<LU_MDO> LU_MDO { get; set; }
        public virtual DbSet<LU_Outlet> LU_Outlet { get; set; }
        public virtual DbSet<LU_ShortNote> LU_ShortNote { get; set; }
        public virtual DbSet<TRN_AssetAuditPhotos> TRN_AssetAuditPhotos { get; set; }
    }
}
