//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinigentAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questionnaire
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Questionnaire()
        {
            this.QuestionnaireHyginePhotos = new HashSet<QuestionnaireHyginePhoto>();
            this.QuestionnaireHygineSignatures = new HashSet<QuestionnaireHygineSignature>();
            this.QuestionnaireObservations = new HashSet<QuestionnaireObservation>();
            this.QuestionnaireObservationFreeHandWritings = new HashSet<QuestionnaireObservationFreeHandWriting>();
            this.QuestionnairePhysicalStocks = new HashSet<QuestionnairePhysicalStock>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int DistributorId { get; set; }
        public System.DateTime Date { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public int CreatorId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int ModifierId { get; set; }
        public System.DateTime ModificationDate { get; set; }
    
        public virtual Distributor Distributor { get; set; }
        public virtual LU_User LU_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionnaireHyginePhoto> QuestionnaireHyginePhotos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionnaireHygineSignature> QuestionnaireHygineSignatures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionnaireObservation> QuestionnaireObservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionnaireObservationFreeHandWriting> QuestionnaireObservationFreeHandWritings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionnairePhysicalStock> QuestionnairePhysicalStocks { get; set; }
    }
}
