//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinigentAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_QuestionnaireHygineSignature
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public string Name { get; set; }
        public int IdentityId { get; set; }
        public string SignaturePhoto { get; set; }
        public string DistributorPhoto { get; set; }
    }
}
