//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinigentAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_SchemeAuditShopDetails_Test
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public string OutlateName { get; set; }
        public int GccCode { get; set; }
        public string RetailSellerName { get; set; }
        public string MobileNumber { get; set; }
        public string OutlateTypeId { get; set; }
        public System.DateTime VisitedDate { get; set; }
        public string DistributorName { get; set; }
        public int AsmId { get; set; }
        public int AicId { get; set; }
        public string OutlateAddress { get; set; }
    }
}
