//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinigentAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_QuestionnairePhysicalStock
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public int ItemId { get; set; }
        public decimal SystemStock { get; set; }
        public decimal PhysicalStock { get; set; }
        public decimal Difference { get; set; }
        public decimal BBDDamage { get; set; }
        public int IssueId { get; set; }
    }
}
