//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinigentAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_Scheme_Audit_Child_t
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public string ImageLocation { get; set; }
        public Nullable<short> IsSignature { get; set; }
    }
}
