//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinigentAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_QuestionnaireStockIssueFreeHandwriting
    {
        public int Id { get; set; }
        public int QuestionnaireId { get; set; }
        public int PhysicalStockId { get; set; }
        public int IssueId { get; set; }
        public string Issue { get; set; }
    
        public virtual TRN_QuestionnaireObservationFreeHandWriting TRN_QuestionnaireObservationFreeHandWriting { get; set; }
    }
}
