//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinigentAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_PermissionDetail
    {
        public long PermissionDetailId { get; set; }
        public long PermissionId { get; set; }
        public int ScreenDetailId { get; set; }
        public bool CanExecute { get; set; }
    
        public virtual LU_ScreenDetail LU_ScreenDetail { get; set; }
        public virtual TRN_Permission TRN_Permission { get; set; }
    }
}
