//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinigentAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_Permission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRN_Permission()
        {
            this.TRN_PermissionDetail = new HashSet<TRN_PermissionDetail>();
        }
    
        public long PermissionId { get; set; }
        public int UserGroupId { get; set; }
        public int ScreenId { get; set; }
        public bool CanView { get; set; }
        public int CreatorId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int UpdatorId { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual LU_Screen LU_Screen { get; set; }
        public virtual LU_UserGroup LU_UserGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_PermissionDetail> TRN_PermissionDetail { get; set; }
    }
}
