//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinigentBackend.SECURITY.SecurityEntity
{
    using System;
    using System.Collections.Generic;
    
    public class AssetInfo
    {
        public int Id { get; set; }
        public string AssetNumber { get; set; }
        public string SerialNumber { get; set; }
        public string DistributorId { get; set; }
        public string DistributorName { get; set; }
        public int AICId { get; set; }
        public string AICName { get; set; }
        public int ASMId { get; set; }
        public string ASMName { get; set; }
        public string MDOId { get; set; }
        public string MDOName { get; set; }
        public string OutletId { get; set; }
        public string OutletName { get; set; }
        public string OutletAddress{ get; set; }
        public string ContactNumber { get; set; }
        public int CoolerId { get; set; }
        public string CoolerModel { get; set; }
      
    }
}
