//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinigentBackend.SECURITY.SecurityEntity
{
    using System;
    using System.Collections.Generic;
    
    public class TRN_AssetAuditPhotos
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public int AssetInfoId { get; set; }
        public string ShopImage { get; set; }
        public string AssetImage { get; set; }
        public string SignImage { get; set; }
    }
}
