//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinigentBackend.SECURITY.SecurityEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_QuestionnaireDetails
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public bool LogoOfTheTCC { get; set; }
        public string LogoImage { get; set; }
        public bool StorageOfMemoForLastYear { get; set; }
        public string MemoImage { get; set; }
        public bool GitInIdasAvailable { get; set; }
        public string GitImage { get; set; }
        public bool DayClosePending { get; set; }
        public string DayCloseImage { get; set; }
        public bool StorageCondition { get; set; }
        public bool MarketReturnedProductAdjusted { get; set; }
        public bool FreeSchemeProductAvailable { get; set; }
        public int MaintainingMandateTime { get; set; }
    
   
    }
}
